# Generated by Django 4.1.1 on 2022-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.PositiveIntegerField()),
                ('emp_age', models.PositiveIntegerField()),
                ('emp_city', models.CharField(max_length=20)),
            ],
        ),
    ]
